import Head from 'next/head'
import{BsFillMoonStarsFill} from 'react-icons/bs'
import  {AiFillTwitterCircle,AiFillLinkedin,AiFillYoutube} from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png'
import consulting from  '../public/consulting.png'
import design from '../public/design.png';
import code from "../public/code.png"
import web1 from '../public/web1.png'


export default function Home() {
  return (
    <div >
      <Head>  
        <title>vishnu karthik portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-10 md:text-center md:px-20 lg:px-60'>
        <section className=' min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between' >
            <h1 className=' text-xl font-burtons'>developed by karthik</h1>
            <ul className=' flex items-center'> 
              <li>
                <BsFillMoonStarsFill  className=' cursor-pointer text-2xl'/>
              </li>
              <li>
                <a href='#' className=' bg-gradient-to-r  from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className=' text-center p-10' >
            <h2 className='text-5xl py-2 text-teal-500 font-medium' >vishnu karthik</h2>
            <h3 className=' text-2xl py-2 ' >student 3rd year</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-3xl'>student form ECE wish to work in software development</p>
          </div>

          <div className=' text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle/>
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className=' relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={deved} layout ='fill' objectfit = 'cover' /> 
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1' >Technologies I know</h3>
            <p className='text-md py-2 leading-8 text-gray-800' > <span className=' text-teal-500'>Python </span> (Intermediate)  C (Intermediate) C++ (Basic) Java (Basic) Velocity (Basic) </p>
          </div>

          <div className='lg:flex gap-10'>
            <div className='text-center grid place-items-center content-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1'>
              <Image className=' ' src={design}   width={100} height={100}/>
              <h3 className=' text-lg font-medium pt-8 pb-2' ></h3>
              <p className='py-4 text-teal-600'>Technologies I know</p>
              <p className='text-gray-800 py-1'>Python</p>
              <p className='text-gray-800 py-1'>Java</p>
              <p className='text-gray-800 py-1'>C ,C++</p>
            </div>
            <div className='text-center grid place-items-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1'>
              <Image src={code}   width={100} height={100}/>
              <h3 className=' text-lg font-medium pt-8 pb-2' ></h3>
              <p className='py-4 text-teal-600'>Technologies I know</p>
              <p className='text-gray-800 py-1'>Python</p>
              <p className='text-gray-800 py-1'>Java</p>
              <p className='text-gray-800 py-1'>C ,C++</p>
            </div>
            
          </div>

          <div>
            <h3 className=' text-3xl py-1 '>portfolio</h3>
            <p className=' text-md py-2 leading-8 text-gray-800'>
              Programmer and a passionate learner who's always willing to learn and work across different
              technologies and domains. Completed my undergraduate Bachelor's degree
            </p>

            <div>
              <div>
                <Image src = {web1}/>
              </div>
            </div>
          </div>
        </section>
        
      </main>

     
    </div>
  )
}
